// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzpyfkuyjxmczspqdxkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6cHlma3V5anhtY3pzcHFkeGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzkxMDEsImV4cCI6MjA3MTg1NTEwMX0.VVeUoDpBQWPVtZukAy8H5yaZ__nRNmD7AVUqjClrDtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});